name: Android CI

on:
  push:
    branches: [ "yuyinKT" ]
  pull_request:
    branches: [ "yuyinKT" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: get wenet
      run: git clone https://github.com/wenet-e2e/wenet.git && cd ./wenet && get checkout c11db56b8f3ebb323b8548cf80fd0d36eef5f245 && cd ../

    - name: get assets
      run: chmod +x ./.github/workflows/downloadAssets.sh && ./.github/workflows/downloadAssets.sh

    - name: link code of wenet
      run: chmod +x ./.github/workflows/linkcode.sh && ./.github/workflows/linkcode.sh

    - name: get ass
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
